#!/bin/sh
i="1"
STRING="$1"
LEN=${#STRING}

while [ $i -le $LEN ]
do
CHAR=`printf "$STRING" | cut -c $i-$i`
printf "$CHAR"
il=$[$i-1]
LETTER=${STRING:$il:1}
i=$[$i+1]

if [ "$LETTER" = "." ] || [ "$LETTER" = "!" ] || [ "$LETTER" = "?" ]; then
sleep 0.8
else
sleep 0.07
fi

done
echo ""